---
title: "Introduction to SimplyAgree"
author: "Aaron R. Caldwell"
date: "Last Updated: `r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to SimplyAgree}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The `SimplyAgree` R package was created to make the process of quantifiying measurement agreement, consistency, and reliability. This package expands upon the capabilities of currently available R packages (such as `psych` and `blandr`) by 1) providing support for agreement studies that involve multiple observations (`agree_test` and `agree_reps` functions) 2) provide robust tests of agreement even in simple studies (`shieh_test` output from the `agree_test` function) and 3) a robust set of reliability statistics (`reli_stats` function).

In this vignette I will shortly demonstrate the implementation of each function and *most* of the underlying calculations within each function


# Simple Agreement

In the simpliest scenario, 

# Repeated Measures Agreement

# Advanced Agreement
