
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `R`=list(
        `type`="software", 
        `author`="R Core Team", 
        `year`=2018, 
        `title`="A Language and Envionment for Statistical Computing", 
        `publisher`="[Computer software]. Retrieved from https://cran.r-project.org/", 
        `url`="https://cran.r-project.org/"), 
    `SimplyAgree`=list(
        `type`="article", 
        `author`="Caldwell, A.R.", 
        `year`=2021, 
        `title`="SimplyAgree: An R package and jamovi Module for Simplifying Agreement and Reliability Analyses", 
        `publisher`="Journal of Open Source Software", 
        `url`="https://doi.org/10.21105/joss.04148"))
