# Globals

utils::globalVariables(c("boot_bias",
                         "boot_within_sd",
                         "boot_between_sd",
                         "boot_total_sd",
                         "boot_low_loa",
                         "boot_upper_loa",
                         "vartab",
                         "Condition","X","d",
                         "both_avg", "x_bar", "y_bar",
                         "drop_na", "delta", "is.missing",
                         "CI.n", "power.power", "value",
                         "feature", "name", "stack",
                         "sf", "qf", "items", "values",
                         "avg_both", "stats.final",
                         "LOA.SD", "LOA.mu", "N", "agree.level",
                         "beta.delta", "conf.level", "power",
                         "y1", "upper.ci","lower.ci","estimate",
                         "conf.high", "conf.low", "lcl", "pred",
                         "predicted",
                         "the_int",
                         "the_slope",
                         "ucl", 'y',
                         "mean_y", "n_y",
                         "diff_y2", "n_x",
                         "diff_x", "mean_x",
                         "diff_y", "mean_y",
                         "at", "median", "confint",
                         "binomial", "glm",
                         "binom.test", "failure",
                         "success",
                         "diff_x2",
                         "level",
                         "Var1",
                         "Var2",
                         "Var3",
                         "avg",
                         "bias",
                         "boot_est",
                         "condition",
                         "high",
                         "low",
                         "nboot",
                         "sd_between",
                         "sd_within",
                         "se",
                         "statistic",
                         "std.error",
                         "term",
                         "sd_total",
                         ".",
                         ":="))
