
# This file is automatically generated, you probably don't want to edit this

jmvagreemultiOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvagreemultiOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            method1 = NULL,
            method2 = NULL,
            id = NULL,
            ciWidth = 0.95,
            agreeWidth = 0.95,
            testValue = 2,
            valEq = FALSE, ...) {

            super$initialize(
                package="SimplyAgree",
                name="jmvagreemulti",
                requiresData=TRUE,
                ...)

            private$..method1 <- jmvcore::OptionVariable$new(
                "method1",
                method1,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..method2 <- jmvcore::OptionVariable$new(
                "method2",
                method2,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..id <- jmvcore::OptionVariable$new(
                "id",
                id)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=0.5,
                max=0.999,
                default=0.95)
            private$..agreeWidth <- jmvcore::OptionNumber$new(
                "agreeWidth",
                agreeWidth,
                min=0.5,
                max=0.999,
                default=0.95)
            private$..testValue <- jmvcore::OptionNumber$new(
                "testValue",
                testValue,
                default=2)
            private$..valEq <- jmvcore::OptionBool$new(
                "valEq",
                valEq,
                default=FALSE)

            self$.addOption(private$..method1)
            self$.addOption(private$..method2)
            self$.addOption(private$..id)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..agreeWidth)
            self$.addOption(private$..testValue)
            self$.addOption(private$..valEq)
        }),
    active = list(
        method1 = function() private$..method1$value,
        method2 = function() private$..method2$value,
        id = function() private$..id$value,
        ciWidth = function() private$..ciWidth$value,
        agreeWidth = function() private$..agreeWidth$value,
        testValue = function() private$..testValue$value,
        valEq = function() private$..valEq$value),
    private = list(
        ..method1 = NA,
        ..method2 = NA,
        ..id = NA,
        ..ciWidth = NA,
        ..agreeWidth = NA,
        ..testValue = NA,
        ..valEq = NA)
)

jmvagreemultiResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvagreemultiResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        blandtab = function() private$.items[["blandtab"]],
        ccctab = function() private$.items[["ccctab"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="jamovi Agreement Analysis for Nested or Replicate Data")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="jamovi Agreement Analysis for Nested or Replicate Data"))
            self$add(jmvcore::Table$new(
                options=options,
                name="blandtab",
                title="Zou's MOVER Limits of Agreement",
                rows=3,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="lowerci", 
                        `title`="Lower C.I.", 
                        `type`="number"),
                    list(
                        `name`="upperci", 
                        `title`="Upper C.I", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ccctab",
                title="Concordance Correlation Coefficient",
                rows=1,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="lowerci", 
                        `title`="Lower C.I.", 
                        `type`="number"),
                    list(
                        `name`="upperci", 
                        `title`="Upper C.I", 
                        `type`="number"))))}))

jmvagreemultiBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvagreemultiBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SimplyAgree",
                name = "jmvagreemulti",
                version = c(1,0,0),
                options = options,
                results = jmvagreemultiResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Agreement Analysis for Nested or Replicate Data
#'
#' 
#' @param data .
#' @param method1 .
#' @param method2 .
#' @param id .
#' @param ciWidth a number between .50 and .999 (default: .95), the width of
#'   confidence intervals
#' @param agreeWidth a number between .50 and .999 (default: .95), the width
#'   of agreement limits
#' @param testValue a number specifying the limit of agreement
#' @param valEq .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$blandtab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ccctab} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$blandtab$asDF}
#'
#' \code{as.data.frame(results$blandtab)}
#'
#' @export
jmvagreemulti <- function(
    data,
    method1,
    method2,
    id,
    ciWidth = 0.95,
    agreeWidth = 0.95,
    testValue = 2,
    valEq = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jmvagreemulti requires jmvcore to be installed (restart may be required)")

    if ( ! missing(method1)) method1 <- jmvcore::resolveQuo(jmvcore::enquo(method1))
    if ( ! missing(method2)) method2 <- jmvcore::resolveQuo(jmvcore::enquo(method2))
    if ( ! missing(id)) id <- jmvcore::resolveQuo(jmvcore::enquo(id))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(method1), method1, NULL),
            `if`( ! missing(method2), method2, NULL),
            `if`( ! missing(id), id, NULL))


    options <- jmvagreemultiOptions$new(
        method1 = method1,
        method2 = method2,
        id = id,
        ciWidth = ciWidth,
        agreeWidth = agreeWidth,
        testValue = testValue,
        valEq = valEq)

    analysis <- jmvagreemultiClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

