
# This file is automatically generated, you probably don't want to edit this

jmvreliOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvreliOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            ciWidth = 0.95, ...) {

            super$initialize(
                package="SimplyAgree",
                name="jmvreli",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=0.5,
                max=0.999,
                default=0.95)

            self$.addOption(private$..vars)
            self$.addOption(private$..ciWidth)
        }),
    active = list(
        vars = function() private$..vars$value,
        ciWidth = function() private$..ciWidth$value),
    private = list(
        ..vars = NA,
        ..ciWidth = NA)
)

jmvreliResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvreliResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        icctab = function() private$.items[["icctab"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Reliability Analysis")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Reliability Analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="icctab",
                title="Intraclass Correlation Coefficients",
                rows=6,
                columns=list(
                    list(
                        `name`="model", 
                        `title`="model", 
                        `type`="text"),
                    list(
                        `name`="measures", 
                        `title`="measures"),
                    list(
                        `name`="type", 
                        `title`="type", 
                        `type`="text"),
                    list(
                        `name`="icc", 
                        `title`="ICC", 
                        `type`="number"),
                    list(
                        `name`="lower.ci", 
                        `title`="lower.ci", 
                        `type`="number"),
                    list(
                        `name`="upper.ci", 
                        `title`="upper.ci", 
                        `type`="number"))))}))

jmvreliBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvreliBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SimplyAgree",
                name = "jmvreli",
                version = c(1,0,0),
                options = options,
                results = jmvreliResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Reliability Analysis
#'
#' 
#' @param data the data as a data frame
#' @param vars a list of the column names containing the measurements for
#'   reliability analysis.
#' @param ciWidth a number between .50 and .999 (default: .95), the width of
#'   confidence intervals
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$icctab} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$icctab$asDF}
#'
#' \code{as.data.frame(results$icctab)}
#'
#' @export
jmvreli <- function(
    data,
    vars,
    ciWidth = 0.95) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jmvreli requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- jmvreliOptions$new(
        vars = vars,
        ciWidth = ciWidth)

    analysis <- jmvreliClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

